### PR TITLE
Standardize line endings + Linting

### PR DESCRIPTION
**Pull request by rglara**
* Adding `.gitattributes` to help with LF standardization
  * Updated appropriate files to get them to standard by running `git add --renormalize .` (no content changes)
* Updating linting rules for PR review comments
  * Note that rules will show errors if you use a linting plugin or run `npm run lint` manually; it does not affect compilation

Note: It might be nice to integrate a crowd sourced coding standard (the most popular of which is [AirBnB](https://www.npmjs.com/package/eslint-config-airbnb). I limited this PR just to get something in place.

### CODE REVIEW

**Comment by paulbilnoski** [comment]
Thanks!

**Comment by paulbilnoski** [comment]
I pulled in the changes, but on using them I disagree with them. Regarding the .gitattributes, I really dislike tools that add magic, like having the git repo change what you commit. A personal branch or user settings are a better place, I think. Different line endings don't break things, but this setting does make rebases much more painful and goes too far.
As for whitespace, I am not as strongly pro uniform whitespace in the files as I am against tools that take the task out of the mind of the dev. There are many times to bend the rules and I think this goes too far. I've had battles with special cases in code formatters and linting rules for a long time, and I've learned the dev knows better than the tool.
These sorts of things are more appropriate to apply to a new project, not to one several years old that passed through the hands of multiple caretakers. As I have updated certain parts of the app I have cleaned up certain things, but new rules on an old project I think is too much. You are free to update your linting rules and retain them in personal branches, and to reformat code that is touched, but sweeping through existing code with new cleanup rules is more trouble than it is worth.

**Comment by rglara** [comment]
As you are the repo owner, I’ll defer to what you want to do. The updates to revert seem ok to keep the project open to more.

As food for thought, I’ve personally started advocating using tabs, instead of spaces, in my projects after reading this:
https://www.reddit.com/r/javascript/comments/c8drjo/nobody_talks_about_the_real_reason_to_use_tabs/
I was a “4 space” person for a long time prior.

Thanks for your time to maintain and upkeep this effort.

**Comment by paulbilnoski** [comment]
I'm open to using tabs to indent lines instead of 4 or 3 spaces. I've not had someone visually impaired on my team that made that particular case for it, and in my experience do not have a strong like or dislike to either.
As for this project, feel free to update files you touch to replace space indents with tabs. If something comes up that is a good argument as a need for change, I can be convinced. For now, my preference is to leave a file as-is unless there is a need to change something.
Thank again for your contributions to improve the project, and openness to discussion.

**Pull request merged**
